
all:
	gcc test/write_test.c -o ./test/write_test
	#gcc test/rename_test.c -o ./test/rename_test
	#gcc test/setattr_test.c -o ./test/setattr_test
	#gcc test/mknod_test.c -o ./test/mknod_test
	#gcc test/mkdir_test.c -o ./test/mkdir_test
	sudo ./test/write_test

switch_state:
	gcc test/switch_state.c -o ./test/switch_state
	sudo ./test/switch_state

init_blacklist:
	gcc test/init_blacklist.c -o ./test/init_blacklist
	sudo ./test/init_blacklist